version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: java-springboot-thon
    ports:
      - "5432:5432"
    networks:
      - thon-network
  java-springboot-thon:
    image: thonwelling/java-springboot-thon
    restart: always
    build: ./java-springboot-thon
    working_dir: /java-springboot-thon
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/java-springboot-thon
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "80:80"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - thon-network
networks:
  thon-network:
    driver: bridge