version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: java-springboot-thon
    ports:
      - "5432:5432"
    networks:
      - thon-network
  rest-with-spring-boot-java:
    image: thonwelling/java-springboot-thon
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/java-springboot-thon
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "80:80"
    command: java -jar /app/rest-with-spring-boot-java.jar
    depends_on:
      - db
    networks:
      - thon-network
networks:
  thon-network:
    driver: bridge