
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://thonwelling.com.br
spring:
  config:
    actives: default
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_thonwelling2
    username: postgres
    password: postgres

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        springdoc:
          pathsToMach:/api/**/v1/**
        swagger-ui:
          use-root-path: true