cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://thonwelling.com.br
file:
  upload-dir: /projetos/upload-spring
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  config:
    actives: default
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java-springboot-thon
    username: postgres
    password: postgres

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  springdoc:
    pathsToMach:
      -/auth/**
      -/api/**/v1/**
  swagger-ui:
    use-root-path: true